# Generated by Django 4.2.3 on 2023-07-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Polling',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='polling',
        ),
    ]
