# Generated by Django 4.2.3 on 2023-07-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_polling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polling',
            old_name='question_text',
            new_name='polling_text',
        ),
    ]
